### ISSUE TITLE
Error in Google_earth_matlab_generator.m

### ISSUE THREAD

**Issue by x0aashish** [PrzemyslawHausman/VISUALIZATION-OF-FLIGHT-TRAJECTORY-IN-GOOGLE-EARTH-PRO-AND-MATLAB#1]
Error: Could not open file GPS.TXT file.

Where is this gps.txt file and how can I open it?

**Comment by PrzemyslawHausman** [comment]
W dniu 2023-10-18 08:45, Aashish Yadav napisał(a):
> Error: Could not open file GPS.TXT file.
> 
> Where is this gps.txt file and how can I open it?
> 
Hi! I made whole app for trajectories so it would be much much easier to 
process, and also some bugs were fixed. I will update this on github 
this week. Stay tuned!

**Comment by x0aashish** [comment]
> W dniu 2023-10-18 08:45, Aashish Yadav napisał(a):
> Error: Could not open file GPS.TXT file. Where is this gps.txt file and how can I open it?
> Hi! I made whole app for trajectories so it would be much much easier to process, and also some bugs were fixed. I will update this on github this week. Stay tuned!

Hi PrzemyslawHausman
Thank you for updating the library. It was really insightful and fun to play with it.
All issues quoted earlier were fixed and thank you for sharing the updated version. 

Regards
